repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: [ 'click==8.0.4' ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        name: mypy
        entry: pipenv run mypy --config-file ./mypy.ini
        language: python
        'types_or': [ python, pyi ]
        args: [ "--ignore-missing-imports", "--scripts-are-modules", "--install-types", "--non-interactive" ]
        require_serial: true
        additional_dependencies: [ ]
        minimum_pre_commit_version: '2.9.2'
